apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-web-app
spec:
  selector:
    matchLabels:
      app: dotnet-web-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dotnet-web-app
    spec:
      containers:
      - image: aphiwe2020/dotnet-web-app:1.0.11
        name: dotnet-web-app
        ports:
        - containerPort: 7146
          name: dotnet-web-app
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-web-app-svc
spec:
  ports:
  - port: 7146
    targetPort: 80
  selector:
    app: dotnet-web-app
  externalTrafficPolicy: Local
  type: LoadBalancer